import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TodosProvider from "@/providers/TodosProvider";
import { getData } from "@/lib/actions";


export const metadata: Metadata = {
  title: "Next Stream Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const todosDataPromise = getData()
  return (
    <html lang="en">
      <body>
        <TodosProvider todosPromise={todosDataPromise} >
          {children}
        </TodosProvider>

      </body>
    </html>
  );
}
